---
build_from:
  aarch64: ghcr.io/erik73/base/aarch64:5.0.7
  amd64: ghcr.io/erik73/base/amd64:5.0.7
  armv7: ghcr.io/erik73/base/armv7:5.0.7
  armhf: ghcr.io/erik73/base/armhf:5.0.7
  i386: ghcr.io/erik73/base/i386:5.0.7
