---
build_from:
  aarch64: ghcr.io/erik73/base/aarch64:4.0.4
  amd64: ghcr.io/erik73/base/amd64:4.0.4
  armv7: ghcr.io/erik73/base/armv7:4.0.4
  armhf: ghcr.io/erik73/base/armhf:4.0.4
  i386: ghcr.io/erik73/base/i386:4.0.4
