---
build_from:
  aarch64: ghcr.io/erik73/base/aarch64:3.0.12
  amd64: ghcr.io/erik73/base/amd64:3.0.12
  armv7: ghcr.io/erik73/base/armv7:3.0.13
  armhf: ghcr.io/erik73/base/armhf:3.0.13
  i386: ghcr.io/erik73/base/i386:3.0.13
