---
build_from:
  aarch64: ghcr.io/erik73/base/aarch64:5.0.1
  amd64: ghcr.io/erik73/base/amd64:5.0.1
  armv7: ghcr.io/erik73/base/armv7:5.0.1
  armhf: ghcr.io/erik73/base/armhf:5.0.1
  i386: ghcr.io/erik73/base/i386:5.0.1
