---
build_from:
  aarch64: ghcr.io/erik73/base/aarch64:2.0.12
  amd64: ghcr.io/erik73/base/amd64:2.0.12
  armv7: ghcr.io/erik73/base/armv7:2.0.12
  armhf: ghcr.io/erik73/base/armhf:2.0.12
  i386: ghcr.io/erik73/base/i386:2.0.12
